name: fetch-player
on: [push, pull_request]

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          echo "Fetched secret: $STEAM_API_KEY"

        env:
          GH_TOKEN: ${{ secrets.STEAM_API_KEY }}