name: Get secert for STEAM_API_KEY
on: [push, pull_request]

# env:
#   TESTING_API_KEY: ${{ secrets.TESTING_API_KEY }}

jobs:
  get-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action
        env: # Or as an environment variable
            TESTING_API_KEY: ${{ secrets.TESTING_API_KEY }}
        uses: actions/checkout@main
      - run: |
            echo "TESTING_API_KEY=$TESTING_API_KEY"
            python cli.py --steam-users aaronleao --api-key TESTING_API_KEY --display-player
